version: '3.6'

networks:
  default:
    external: true
    name: mybridge
    
volumes:
  data:

services:
  elastic:
    build:
      context: .
    container_name: elastic
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
    volumes:
      - data:/usr/share/elasticsearch/data
