version: '3.6'
services:

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Langeoog1#
      - MYSQL_PASSWORD=Langeoog1#
      - MYSQL_DATABASE=dbKLAUDnc
      - MYSQL_USER=ncadmin
      
  nc:
    image: nextcloud:fpm
    volumes:
      - nextcloud:/var/www/html
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=Langeoog1#
      - MYSQL_DATABASE=dbKLAUDnc
      - MYSQL_USER=ncadmin
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=1G
      - PHP_UPLOAD_LIMIT=8G
      - TRUSTED_PROXIES=172.0.0.0/8
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html
    restart: unless-stopped  
    
networks:
  default:
    external: true
    name: mybridge
    
volumes:
  db:
  nextcloud:
  redis:
